### ISSUE TITLE
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'

### ISSUE THREAD

**Issue by andreyplotkin** [sarathsp06/exotel-py#2]
Latest version of exotel (0.1.1) has strict dependency on requests-2.2.1
requests==2.2.1 in its turn uses old version of urllib3, which uses PROTOCOL_SSLv3.
This protocol was disabled in new versions of Debian, so elastalert can't be installed properly in new versions of Debian.

> Searching for requests==2.2.1
Reading https://pypi.python.org/simple/requests/
Best match: requests 2.2.1
Downloading https://pypi.python.org/packages/d1/0c/2dc2996268bc64b531a5a2dc6f4ec04552f3a8a2a86e88aeedcb92987741/requests-2.2.1.tar.gz#md5=ac27081135f58d1a43e4fb38258d6f4e
Processing requests-2.2.1.tar.gz
Writing /tmp/easy_install-OR0w1y/requests-2.2.1/setup.cfg
Running requests-2.2.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-OR0w1y/requests-2.2.1/egg-dist-tmp-isp4Tf
Traceback (most recent call last):
File "setup.py", line 43, in 
'stomp.py'
File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
dist.run_commands()
File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
self.run_command(cmd)
File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
cmd_obj.run()
File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 67, in run
self.do_egg_install()
File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
cmd.run()
File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 414, in run
self.easy_install(spec, not self.no_deps)
File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 644, in easy_install
return self.install_item(None, spec, tmpdir, deps, True)
File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 695, in install_item
self.process_distribution(spec, dist, deps)
File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 740, in process_distribution
[requirement], self.local_index, self.easy_install
File "/usr/lib/python2.7/dist-packages/pkg_resources/init.py", line 826, in resolve
dist = best[req.key] = env.best_match(req, ws, installer)
File "/usr/lib/python2.7/dist-packages/pkg_resources/init.py", line 1092, in best_match
return self.obtain(req, installer)
File "/usr/lib/python2.7/dist-packages/pkg_resources/init.py", line 1104, in obtain
return installer(requirement)
File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 663, in easy_install
return self.install_item(spec, dist.location, tmpdir, deps)
File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 693, in install_item
dists = self.install_eggs(spec, download, tmpdir)
File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 873, in install_eggs
return self.build_and_install(setup_script, setup_base)
File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1101, in build_and_install
self.run_setup(setup_script, setup_base, args)
File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1087, in run_setup
run_setup(setup_script, args)
File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 246, in run_setup
raise
File "/usr/lib/python2.7/contextlib.py", line 35, in exit
self.gen.throw(type, value, traceback)
File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
yield
File "/usr/lib/python2.7/contextlib.py", line 35, in exit
self.gen.throw(type, value, traceback)
File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 166, in save_modules
saved_exc.resume()
File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 141, in resume
six.reraise(type, exc, self._tb)
File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 154, in save_modules
yield saved
File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
yield
File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 243, in run_setup
DirectorySandbox(setup_dir).run(runner)
File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 273, in run
return func()
File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 242, in runner
_execfile(setup_script, ns)
File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 46, in _execfile
exec(code, globals, locals)
File "/tmp/easy_install-OR0w1y/requests-2.2.1/setup.py", line 6, in
File "/tmp/easy_install-OR0w1y/requests-2.2.1/requests/init.py", line 53, in 
File "/tmp/easy_install-OR0w1y/requests-2.2.1/requests/packages/urllib3/contrib/pyopenssl.py", line 62, in 
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'

Some system info:
Description: Debian GNU/Linux 8.5 (jessie)
Release: 8.5

pip -V
pip 9.0.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)

pip show requests
Version: 2.13.0

pip show urllib3
Version: 1.20

Further investigation: http://stackoverflow.com/questions/28987891/patch-pyopenssl-for-sslv3-issue

**Comment by sarathsp06** [comment]
it's IST 1:15 AM, will work on this first thing by day

**Comment by sarathsp06** [comment]
Updated the requirements to have `requests==2.13.0`  . I have tested in some configurations it is working fine will test on more machines by day and close the ticket. @andreyp1986   I would appreciate if you could test on your configuration as well

**Comment by andreyplotkin** [comment]
Works like a sharm. Thanks!

> pip install --upgrade exotel
Collecting exotel
  Downloading exotel-0.1.3.tar.gz
Building wheels for collected packages: exotel
  Running setup.py bdist_wheel for exotel ... done
  Stored in directory: /root/.cache/pip/wheels/22/fa/ae/a51466daf8639d97a80e00f6cb6e1f5304cd96ad33fbcc096a
Successfully built exotel
Installing collected packages: exotel
  Found existing installation: exotel 0.1.1
    Uninstalling exotel-0.1.1:
      Successfully uninstalled exotel-0.1.1
Successfully installed exotel-0.1.3
